
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Add_Unit_Price extends javax.swing.JFrame {

    dbhelper db=new dbhelper();
    /**
     * Creates new form AddUnit_Price
     */
    public Add_Unit_Price() {
        initComponents();
         CustAutoIncerment();
         cmbMeter_Type.setEditable(true);
        cmbMeter_Type.setEnabled(true);
        db.getTable(jTable1, "select * from add_unit_price");
      //  db.FillCombo(cmbMeter_Type, "select distinct(Meter_Type) from add_unit_price", "Meter_Type"); 
    }
    
    
     public void Validate()
    {
        if(txtID.getText().equals("")||txtUnit_Rate.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        }
    }
     
      public void clearText()
     {
         txtID.setText("");
         txtUnit_Rate.setText("");
         
     }
     
     
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtUnit_Rate = new javax.swing.JTextField();
        lblID1 = new javax.swing.JLabel();
        lblMeterType = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cmbMeter_Type = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 127, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Add Unit Price");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 90));

        jPanel3.setBackground(new java.awt.Color(255, 127, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID.setText("Unit_Rate");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel3.add(txtUnit_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, 30));

        lblID1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID1.setText("ID");
        jPanel3.add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblMeterType.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblMeterType.setText("Meter_Type");
        jPanel3.add(lblMeterType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 110, 30));

        cmbMeter_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestic", "Commercial" }));
        jPanel3.add(cmbMeter_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 110, 30));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, 280));

        jPanel4.setBackground(new java.awt.Color(255, 127, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Meter_Type", "Unit_Rate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 260));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 420, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        CustAutoIncerment();
       Validate();
        
       
       try
        {
        String s="select Meter_Type from add_unit_price WHERE Meter_Type='"+cmbMeter_Type.getSelectedItem().toString()+"'";
        db.DataFound(s);
     
        if(db.rs.next())
        {
           JOptionPane.showMessageDialog(this, "Meter Type Already Exist please perform update");
           return;
        } 
      
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
       
       
        db.InsertData("insert into add_unit_price(ID,Meter_Type,Unit_Rate)values('"+txtID.getText()+"','"+cmbMeter_Type.getSelectedItem().toString()+"','"+txtUnit_Rate.getText()+"')");
        db.getTable(jTable1, "select * from add_unit_price");
        clearText();
          CustAutoIncerment();
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        db.updateRecord("update add_unit_price set Unit_Rate='"+txtUnit_Rate.getText()+"' where  Meter_Type='"+cmbMeter_Type.getSelectedItem().toString()+"'");
             db.getTable(jTable1, "select * from add_unit_price");
             clearText();
             CustAutoIncerment();
             
    }//GEN-LAST:event_btnUpdateActionPerformed

   public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from add_unit_price";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }  
    
    
      
    
    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Unit_Price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Unit_Price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Unit_Price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Unit_Price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Unit_Price().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbMeter_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblMeterType;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtUnit_Rate;
    // End of variables declaration//GEN-END:variables
}
