
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Assign_Bills extends javax.swing.JFrame {
String MeterType="",Rate="";
    dbhelper db=new dbhelper();
String strDate="";

    /**
     * Creates new form Assign_Bills
     */
    public Assign_Bills() {
        initComponents();
        CustAutoIncerment();
       
        
    }
    
    
    public void calcul()
    {
        double punit,cunit,funit;
        punit=Double.parseDouble(txtPrevious_Unit.getText().toString());
         cunit=Double.parseDouble(txtCurrent_Unit.getText().toString());
         funit=cunit-punit;
         txtFinalUnit.setText(String.valueOf(funit));
         
              CalculateAmt();
    }
    
    public void Validate()
    {
        if(txtID.getText().equals("")|| txtCID_MID.getText().equals("")|| txtPrevious_Unit.getText().equals("")|| txtCurrent_Unit.getText().equals("")||txtFinalUnit.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this, "Please enter all fields");
        }
    }
    
    
    public void clearText()
     {
         txtID.setText("");
        txtCID_MID.setText("");
        txtPrevious_Unit.setText("");
        txtCurrent_Unit.setText("");
        txtFinalUnit.setText("");
       // txtLast_Date.setText(""); 
     }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLast_Date = new javax.swing.JLabel();
        txtCID_MID = new javax.swing.JTextField();
        lblID1 = new javax.swing.JLabel();
        lblID2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPrevious_Unit = new javax.swing.JTextField();
        lblPrevious_Unit = new javax.swing.JLabel();
        lblNO_Of_Unit = new javax.swing.JLabel();
        txtCurrent_Unit = new javax.swing.JTextField();
        txtFinalUnit = new javax.swing.JTextField();
        lblFinal = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMonth = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        dt = new com.toedter.calendar.JDateChooser();
        btnGetData = new javax.swing.JButton();
        lblAmount = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 127, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Assign Bills");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 900, 80));

        jPanel3.setBackground(new java.awt.Color(255, 127, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLast_Date.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblLast_Date.setText("Last Date");
        jPanel3.add(lblLast_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        txtCID_MID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCID_MIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtCID_MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 90, 30));

        lblID1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID1.setText("ID");
        jPanel3.add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblID2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID2.setText("Meter Id");
        jPanel3.add(lblID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 30));

        txtPrevious_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrevious_UnitActionPerformed(evt);
            }
        });
        jPanel3.add(txtPrevious_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 90, 30));

        lblPrevious_Unit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblPrevious_Unit.setText("Previous Unit");
        jPanel3.add(lblPrevious_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        lblNO_Of_Unit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblNO_Of_Unit.setText("Current Unit");
        jPanel3.add(lblNO_Of_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        txtCurrent_Unit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCurrent_UnitFocusLost(evt);
            }
        });
        txtCurrent_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrent_UnitActionPerformed(evt);
            }
        });
        jPanel3.add(txtCurrent_Unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 100, 30));

        txtFinalUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalUnitActionPerformed(evt);
            }
        });
        jPanel3.add(txtFinalUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, 30));

        lblFinal.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblFinal.setText("Final Unit");
        jPanel3.add(lblFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        btnCancel.setText("CANCEL");
        jPanel3.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        lblMonth.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblMonth.setText("Month");
        jPanel3.add(lblMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel3.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 90, 30));
        jPanel3.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 130, 30));

        btnGetData.setText("Get Data");
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnGetData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 30));

        lblAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAmount.setText("Amount");
        jPanel3.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        lblAmount2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAmount2.setText("Amount");
        jPanel3.add(lblAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        jPanel3.add(cmbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 900, 200));

        jPanel4.setBackground(new java.awt.Color(255, 127, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ConsID_MeterID", "Previous_Unit", "NO_OF_Unit", "Amount", "Last_Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 190));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 900, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCID_MIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCID_MIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCID_MIDActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPrevious_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrevious_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrevious_UnitActionPerformed

    private void txtCurrent_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrent_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrent_UnitActionPerformed

    private void txtFinalUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalUnitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        CustAutoIncerment();
        Validate();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        String  date= sdf.format(dt.getDate()) ;

        System.out.println(date);

         db.InsertData("insert into assign_bills(ID,ConsID_MeterID,Previous_Unit,Current_unit,Amount,Last_Date,Status,Month)values('"+txtID.getText()+"','"+txtCID_MID.getText()+"','"+txtPrevious_Unit.getText()+"','"+txtCurrent_Unit.getText()+"','"+txtAmount.getText()+"','"+date+"','Pending','"+cmbMonth.getSelectedItem().toString()+"')");
       db.getTable(jTable1, "select * from assign_bills where ConsID_MeterID='"+txtCID_MID.getText()+"' ");
        clearText();
          CustAutoIncerment();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtCurrent_UnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCurrent_UnitFocusLost
     calcul();

    }//GEN-LAST:event_txtCurrent_UnitFocusLost

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
      try
      {
          db.getRecords("Select Current_unit from assign_bills where ConsID_MeterID='"+txtCID_MID.getText()+"'");
          while(db.rs.next())
          {
              String PUnit=db.rs.getString("Current_unit");
              txtPrevious_Unit.setText(PUnit);
          }
          
      }
      catch(Exception ex)
      {
          System.out.println(ex);
      }
      
           try
      {
          db.getRecords("Select * from consumer_details where Meter_ID='"+txtCID_MID.getText()+"'");
          if(db.rs.next())
          {
            MeterType=db.rs.getString("Meter_Type");
        System.out.println(MeterType);
          }
          else
          {
              JOptionPane.showMessageDialog(this, "Invalid ConsumerId");
              return;
          }
          
      }
      catch(Exception ex)
      {
          System.out.println(ex);
      }
      
     getRate();
       db.getTable(jTable1, "select * from assign_bills where ConsID_MeterID='"+txtCID_MID.getText()+"' ");
    }//GEN-LAST:event_btnGetDataActionPerformed

    public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from assign_bills";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }   
    
    public void getRate()
    {
               try
      {
          System.out.println(MeterType);
          db.getRecords("Select * from add_unit_price where Meter_Type='"+MeterType+"'");
          if(db.rs.next())
          {
              Rate=db.rs.getString("Unit_Rate");
       
          }
          
      }
      catch(Exception ex)
      {
          System.out.println(ex);
      }
    }
    
    
    public void CalculateAmt()
    {
        Double Rates=Double.parseDouble(Rate);
        Double finalUnit=Double.parseDouble(txtFinalUnit.getText());
        
        Double Amt=Rates*finalUnit;
        txtAmount.setText(String.valueOf(Amt));
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assign_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assign_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assign_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assign_Bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assign_Bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbMonth;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblLast_Date;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblNO_Of_Unit;
    private javax.swing.JLabel lblPrevious_Unit;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCID_MID;
    private javax.swing.JTextField txtCurrent_Unit;
    private javax.swing.JTextField txtFinalUnit;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrevious_Unit;
    // End of variables declaration//GEN-END:variables
}
