
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Bill_Payment extends javax.swing.JFrame {

    dbhelper db=new dbhelper();
     String m_where;
    String m_report_source = "/MSEB/";
    String m_sql_stmt;
    Map parametersMap = new HashMap(); 
    /**
     * Creates new form Bill_Payment
     */
    public Bill_Payment() {
        initComponents();
        CustAutoIncerment();
        lblBillId.setText("0");
       // jTable1.isEditing(false);
       jTable1.setDefaultEditor(Object.class, null);
       txtTot_Amount_Paid.setEnabled(false);
       txtTot_Amount.setEditable(false);
        
    }
    
    public void Validate()
    {
        if(txtID.getText().equals("")|| txtCID_MID.getText().equals("")||  txtTot_Amount_Paid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter all feilds");
            return;
        }
    }
    
     public void clearText()
     {
         txtID.setText("");
        txtCID_MID.setText("");
       
        txtTot_Amount_Paid.setText("");
     }
     
     public void Show()
    {
         try {
            DBUtilities dbUtilities = new DBUtilities();
            InputStream is = getClass().getResourceAsStream(m_report_source);

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(m_sql_stmt);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, dbUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (SQLException | JRException e) {
            System.out.println("Exception message " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAmount_Paid = new javax.swing.JLabel();
        txtCID_MID = new javax.swing.JTextField();
        lblBillId = new javax.swing.JLabel();
        lblCID_MID = new javax.swing.JLabel();
        txtTot_Amount_Paid = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnGetData = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        dt = new com.toedter.calendar.JDateChooser();
        txtTot_Amount = new javax.swing.JTextField();
        lblAmount_Paid1 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        lblAmount_Paid2 = new javax.swing.JLabel();
        lblID2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 127, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Bill Payment");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 80));

        jPanel3.setBackground(new java.awt.Color(255, 127, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAmount_Paid.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAmount_Paid.setText("For Month");
        jPanel3.add(lblAmount_Paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        jPanel3.add(txtCID_MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, 30));

        lblBillId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblBillId.setText("BillId");
        jPanel3.add(lblBillId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblCID_MID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblCID_MID.setText("Consumer ID/Meter ID");
        jPanel3.add(lblCID_MID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel3.add(txtTot_Amount_Paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, 30));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 130, 30));

        lblDate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblDate.setText("Payment Date");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnGetData.setText("Get Data");
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnGetData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        btnReport.setText("Report");
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel3.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));
        jPanel3.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, 30));

        txtTot_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTot_AmountActionPerformed(evt);
            }
        });
        jPanel3.add(txtTot_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 130, 30));

        lblAmount_Paid1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAmount_Paid1.setText("Total Amount Paid");
        jPanel3.add(lblAmount_Paid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        jPanel3.add(txtMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, 30));

        lblAmount_Paid2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAmount_Paid2.setText("Total Amount");
        jPanel3.add(lblAmount_Paid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblID2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID2.setText("ID");
        jPanel3.add(lblID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 440, 350));

        jPanel4.setBackground(new java.awt.Color(255, 127, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Tot_Amount_Paid", "Month", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 330));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 450, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        CheckData();
        CustAutoIncerment();
        Validate();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        String  date= sdf.format(dt.getDate()) ;

        System.out.println(date);
        
        db.InsertData("insert into bill_payment(ID,ConsID_MeterID,Date,Amount_Paid,Month,AssignBillId)values('"+txtID.getText()+"','"+txtCID_MID.getText()+"','"+date+"','"+txtTot_Amount_Paid.getText()+"','"+txtMonth.getText()+"','"+lblBillId.getText()+"')");
            db.updateRecord("update assign_bills set status='Clear' WHERE ID='"+lblBillId.getText()+"' AND ConsID_MeterID='"+txtCID_MID.getText()+"'");
        db.getTable( jTable1, "select * from bill_payment");
     //   clearText();
          CustAutoIncerment();
          
          
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
     
        db.getTable(jTable1, "select Id,Last_Date,Amount,Month,Status from  assign_bills where ConsID_MeterID='"+txtCID_MID.getText()+"' AND Status='Pending'");
    }//GEN-LAST:event_btnGetDataActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
        m_report_source = "rptPayment.jrxml";
        m_sql_stmt = "SELECT bill_payment.`ID` AS bill_payment_ID, bill_payment.`ConsID_MeterID` AS bill_payment_ConsID_MeterID, bill_payment.`Date` AS bill_payment_Date, bill_payment.`Amount_Paid` AS bill_payment_Amount_Paid FROM `bill_payment` bill_payment where  bill_payment.`ConsID_MeterID`='"+txtCID_MID.getText()+"'";
   Show();
    }//GEN-LAST:event_btnReportMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
  DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel(); //create a model
    int selectedRowIndex = jTable1.getSelectedRow(); //get selected row
    int id = (Integer) dtm.getValueAt(selectedRowIndex, 0); //get the primary key to fetch data.
        System.out.println(id);
        lblBillId.setText(String.valueOf(id));
        
           try
        {
        String s="select * from assign_bills Where Id='"+id+"'";
        db.DataFound(s);
       
        if(db.rs.next())
        {
           String LastDAte=db.rs.getString("Month");
           txtMonth.setText(LastDAte);
           txtTot_Amount.setText(db.rs.getString("Amount"));
           txtTot_Amount_Paid.setText(db.rs.getString("Amount"));
           
           
        } 
      
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtTot_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTot_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTot_AmountActionPerformed

    public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from bill_payment";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }  
    
     public void CheckData()
    {
        try
        {
        String s="select * from assign_bills WHERE ConsID_MeterID='"+txtCID_MID.getText()+"'";
        db.DataFound(s);
        
        if(db.rs.next())
        {
           
        } 
        else
        {
            JOptionPane.showMessageDialog(this,"Data Not Found For Consumer Id");
            return;
            
        }
     
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    } 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAmount_Paid;
    private javax.swing.JLabel lblAmount_Paid1;
    private javax.swing.JLabel lblAmount_Paid2;
    private javax.swing.JLabel lblBillId;
    private javax.swing.JLabel lblCID_MID;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblID2;
    private javax.swing.JTextField txtCID_MID;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtTot_Amount;
    private javax.swing.JTextField txtTot_Amount_Paid;
    // End of variables declaration//GEN-END:variables
}
