
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Consumer_Details extends javax.swing.JFrame {
    
    dbhelper db=new dbhelper();

    /**
     * Creates new form Consumer_Details
     */
    public Consumer_Details() {
        initComponents();
        CustAutoIncerment();
        cmbMeter_Type.setEditable(true);
        cmbMeter_Type.setEnabled(true);
         db.getTable(jTable1, "select * from consumer_details");
         db.FillCombo(cmbMeter_Type, "select distinct(Meter_Type) from add_unit_price", "Meter_Type");
    }
    
    public void Validate()
    {
        if(txtC_ID.getText().equals("")|| txtC_Name.getText().equals("")|| txtMeter_ID.getText().equals("")|| txtMObile_NO.getText().equals("")|| txtAdhar_NO.getText().equals("")|| txtAddress.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please eneter all feilds");
        }
    }
    
     public void clearText()
     {
         txtC_ID.setText("");
         txtC_Name.setText("");
         txtMeter_ID.setText("");
         txtMObile_NO.setText("");
         txtAdhar_NO.setText("");
         txtAddress.setText("");
        
         
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblMob_NO = new javax.swing.JLabel();
        txtMeter_ID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtC_ID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtAdhar_NO = new javax.swing.JTextField();
        lblStart_Date = new javax.swing.JLabel();
        cmbMeter_Type = new javax.swing.JComboBox();
        lblMeter_Type = new javax.swing.JLabel();
        txtC_Name = new javax.swing.JTextField();
        lblMeter_ID2 = new javax.swing.JLabel();
        lblAdhar_NO1 = new javax.swing.JLabel();
        txtMObile_NO = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        BTNDelete = new javax.swing.JButton();
        dt = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 127, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Consumer Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 90));

        jPanel3.setBackground(new java.awt.Color(255, 127, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMob_NO.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblMob_NO.setText("Mobile NO.");
        jPanel3.add(lblMob_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        txtMeter_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeter_IDActionPerformed(evt);
            }
        });
        jPanel3.add(txtMeter_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 110, 30));

        lblID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID.setText("Consumer ID");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtC_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC_IDActionPerformed(evt);
            }
        });
        jPanel3.add(txtC_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 110, 30));

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblName.setText("Consumer Name");
        jPanel3.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        txtAdhar_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdhar_NOActionPerformed(evt);
            }
        });
        jPanel3.add(txtAdhar_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 160, 30));

        lblStart_Date.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblStart_Date.setText("Satrt Date");
        jPanel3.add(lblStart_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        cmbMeter_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestic", "Commercial" }));
        jPanel3.add(cmbMeter_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, 30));

        lblMeter_Type.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblMeter_Type.setText("Meter Type");
        jPanel3.add(lblMeter_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        txtC_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC_NameActionPerformed(evt);
            }
        });
        jPanel3.add(txtC_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 110, 30));

        lblMeter_ID2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblMeter_ID2.setText("Meter ID");
        jPanel3.add(lblMeter_ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        lblAdhar_NO1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAdhar_NO1.setText("Adhar NO.");
        jPanel3.add(lblAdhar_NO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        txtMObile_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMObile_NOActionPerformed(evt);
            }
        });
        jPanel3.add(txtMObile_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 160, 30));

        lblAddress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAddress.setText("Address");
        jPanel3.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel3.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, 30));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        btnUpdate.setText("UPDATE");
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        BTNDelete.setText("DELETE");
        jPanel3.add(BTNDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));
        jPanel3.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 900, 230));

        jPanel4.setBackground(new java.awt.Color(255, 127, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Consumer_ID", "Comsumer_Name", "Meter_ID", "Meter_Type", "Mobile_NO", "Adhar_NO", "Address", "Start_Date"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 170));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 900, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMeter_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeter_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMeter_IDActionPerformed

    private void txtC_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC_IDActionPerformed

    private void txtAdhar_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdhar_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdhar_NOActionPerformed

    private void txtC_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC_NameActionPerformed

    private void txtMObile_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMObile_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMObile_NOActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      
        Validate();
        CustAutoIncerment();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        String  date= sdf.format(dt.getDate()) ;

        System.out.println(date);
        
        db.InsertData("insert into consumer_details(ID,Name,Meter_ID,Meter_Type,Mobile_NO,Adhar_NO,Address,Star_Date)values('"+txtC_ID.getText()+"','"+txtC_Name.getText()+"','"+txtMeter_ID.getText()+"','"+cmbMeter_Type.getSelectedItem().toString()+"','"+txtMObile_NO.getText()+"','"+txtAdhar_NO.getText()+"','"+txtAddress.getText()+"','"+date+"')");
        db.getTable(jTable1, "select * from consumer_details");
         clearText();
          CustAutoIncerment();
        
    }//GEN-LAST:event_btnAddActionPerformed

     public void CustAutoIncerment()
    {
        try
        {
        String s="select MAX(Id) from consumer_details";
        db.DataFound(s);
        int i=0;
        while(db.rs.next())
        {
           i=db.rs.getInt(1);
        } 
       txtC_ID.setText(String.valueOf(i+1));
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }   
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consumer_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consumer_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consumer_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consumer_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consumer_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDelete;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbMeter_Type;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdhar_NO1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMeter_ID2;
    private javax.swing.JLabel lblMeter_Type;
    private javax.swing.JLabel lblMob_NO;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStart_Date;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdhar_NO;
    private javax.swing.JTextField txtC_ID;
    private javax.swing.JTextField txtC_Name;
    private javax.swing.JTextField txtMObile_NO;
    private javax.swing.JTextField txtMeter_ID;
    // End of variables declaration//GEN-END:variables
}
