
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajan
 */
public class Report_Option extends javax.swing.JFrame {
 dbhelper db=new dbhelper();
     String m_where;
    String m_report_source = "/MSEB/";
    String m_sql_stmt;
    Map parametersMap = new HashMap();  
    /**
     * Creates new form Report_Option
     */
    public Report_Option() {
        initComponents();
    }
    
     public void Show()
    {
         try {
            DBUtilities dbUtilities = new DBUtilities();
            InputStream is = getClass().getResourceAsStream(m_report_source);

            JRDesignQuery jrDesignQuery = new JRDesignQuery();
            jrDesignQuery.setText(m_sql_stmt);

            JasperDesign jasperDesign = JRXmlLoader.load(is);
            jasperDesign.setQuery(jrDesignQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, dbUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (SQLException | JRException e) {
            System.out.println("Exception message " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUnit_Price = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAssign_Bills = new javax.swing.JLabel();
        lblBill_Pmt = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCons_Details = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUnit_Price.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblUnit_Price.setForeground(new java.awt.Color(51, 0, 51));
        lblUnit_Price.setText("Unit Price Report");
        lblUnit_Price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUnit_PriceMouseClicked(evt);
            }
        });
        jPanel2.add(lblUnit_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 70));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAssign_Bills.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        lblAssign_Bills.setForeground(new java.awt.Color(51, 0, 51));
        lblAssign_Bills.setText("Generated Bills Report");
        lblAssign_Bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAssign_BillsMouseClicked(evt);
            }
        });
        jPanel3.add(lblAssign_Bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 70));

        lblBill_Pmt.setBackground(new java.awt.Color(255, 153, 153));
        lblBill_Pmt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPayment.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(51, 0, 51));
        lblPayment.setText("Payment Details");
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
        });
        lblBill_Pmt.add(lblPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(lblBill_Pmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 70));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCons_Details.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblCons_Details.setForeground(new java.awt.Color(51, 0, 51));
        lblCons_Details.setText("Consumer Details");
        lblCons_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCons_DetailsMouseClicked(evt);
            }
        });
        jPanel5.add(lblCons_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblUnit_PriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnit_PriceMouseClicked
           m_report_source = "rptUnit_Price.jrxml";
        m_sql_stmt = "SELECT add_unit_price.`ID` AS add_unit_price_ID,add_unit_price.`Meter_Type` AS add_unit_price_Meter_Type,   add_unit_price.`Unit_Rate` AS add_unit_price_Unit_Rate FROM `add_unit_price` add_unit_price";
   Show();
    }//GEN-LAST:event_lblUnit_PriceMouseClicked

    private void lblAssign_BillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAssign_BillsMouseClicked
        m_report_source = "rptBill.jrxml";
        m_sql_stmt = "SELECT assign_bills.`ID` AS assign_bills_ID, assign_bills.`ConsID_MeterID` AS assign_bills_ConsID_MeterID, assign_bills.`Previous_Unit` AS assign_bills_Previous_Unit, assign_bills.`Current_unit` AS assign_bills_Current_unit, assign_bills.`Amount` AS assign_bills_Amount, assign_bills.`Last_Date` AS assign_bills_Last_Date FROM `assign_bills` assign_bills WHERE assign_bills.`Status`='Pending'";
   Show();
    }//GEN-LAST:event_lblAssign_BillsMouseClicked

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
       m_report_source = "rptPayment.jrxml";
        m_sql_stmt = "SELECT bill_payment.`ID` AS bill_payment_ID, bill_payment.`ConsID_MeterID` AS bill_payment_ConsID_MeterID, bill_payment.`Date` AS bill_payment_Date, bill_payment.`Amount_Paid` AS bill_payment_Amount_Paid FROM `bill_payment` bill_payment";
   Show();
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblCons_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCons_DetailsMouseClicked
       m_report_source = "rptConsumer.jrxml";
        m_sql_stmt = "SELECT consumer_details.`ID` AS consumer_details_ID, consumer_details.`Name` AS consumer_details_Name, consumer_details.`Meter_ID` AS consumer_details_Meter_ID, consumer_details.`Meter_Type` AS consumer_details_Meter_Type, consumer_details.`Mobile_NO` AS consumer_details_Mobile_NO, consumer_details.`Adhar_NO` AS consumer_details_Adhar_NO, consumer_details.`Address` AS consumer_details_Address, consumer_details.`Star_Date` AS consumer_details_Star_Date FROM `consumer_details` consumer_details";
   Show();
    }//GEN-LAST:event_lblCons_DetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAssign_Bills;
    private javax.swing.JPanel lblBill_Pmt;
    private javax.swing.JLabel lblCons_Details;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblUnit_Price;
    // End of variables declaration//GEN-END:variables
}
